src/Carrier.CMS/Areas/Admin/Models/ListCarView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Carrier.CMS.Models
{
    public class ListCarView
    {
        public string Enterprise { get; set; }
        public int TotalCar { get; set; }
        public int TotalDriver { get; set; }
    }
}

src/Carrier.CMS/Areas/Enterprise/Models/EDriverViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Carrier.CMS.Models
{
    public class EDriverViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
        public string BirthDay { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Status { get; set; }
        public DateTime? Created_At { get; set; }
        public DateTime? Updated_At { get; set; }
        public string Front_Image { get; set; }
        public string Back_Image { get; set; }
        public string User_Name { get; set; }
        public bool LockoutEnabled { get; set; }
        public string License { get; set; }
        public Nullable<double> Payload { get; set; }
    }
}

src/Carrier.CMS/Areas/Enterprise/Controllers/EDriverController.cs
using Carrier.CMS.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using Carrier.Utilities;
using Carrier.Models.Entities;
using Carrier.Repository;
using Carrier.CMS;
using System;
using PagedList;
using System.Threading.Tasks;
using System.Data.Entity.Spatial;
using GoogleMaps.LocationServices;
using Carrier.CMS.Common;
using Microsoft.AspNet.Identity;
using CKSource.FileSystem;
using System.Data.SqlClient;
using System.IO;
using System.Web.Helpers;
using System.Web.Configuration;

namespace CMS.Carrier.Areas.Enterprise.Controllers
{
    public class EDriverController : Controller
    {
        private GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        private GenericUnitOfWork _unitOfWorkTemp = new GenericUnitOfWork();
        private GenericUnitOfWork _unitOfWorkTemp2 = new GenericUnitOfWork();

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        // GET: Enterprise/Driver
        [Authorize]
        public ActionResult Index()
        {
            int organizationId = GetCurrentOrganizatinIdByUserName(User.Identity.Name);
            var usersNameOrganizati = User.Identity.Name;

            List<Driver> result = _unitOfWork.GetRepositoryInstance<Driver>().GetAllRecords().Where(o => o.OrganizationId == organizationId).OrderByDescending(o => o.Name).ToList();
            List<EDriverViewModel> resultView = new List<EDriverViewModel>();
            foreach (var item in result)
            {
                var viewModel = new EDriverViewModel();
                var user = UserManager.FindById(item.UserId);
                DriverCar driverCar = _unitOfWork.GetRepositoryInstance<DriverCar>().GetFirstOrDefaultByParameter(o => o.DriverId == item.Id);
                if (driverCar != null)
                {
                    Car carId = _unitOfWork.GetRepositoryInstance<Car>().GetFirstOrDefaultByParameter(o => o.Id == driverCar.CarId);
                    if (carId != null)
                    {
                        viewModel.License = carId.License;
                        viewModel.Payload = carId.Payload;
                    }
                    else
                    {
                        viewModel.License = "0";
                        viewModel.Payload = 0;
                    }
                }
                else
                {
                    viewModel.License = "0";
                    viewModel.Payload = 0;
                }
                viewModel.Id = item.Id;
                viewModel.Address = item.Address;
                viewModel.Back_Image = item.Back_Image;
                viewModel.BirthDay = item.BirthDay;
                viewModel.Created_At = item.Created_At;
                viewModel.Front_Image = item.Front_Image;
                viewModel.Lng = item.Lng;
                viewModel.Lat = item.Lat;
                viewModel.Name = item.Name;
                viewModel.OrganizationId = item.OrganizationId;
                viewModel.Phone = item.Phone;
                viewModel.Sex = item.Sex;
                viewModel.Status = item.Status;
                viewModel.Updated_At = item.Updated_At;
                viewModel.UserId = item.UserId;
                if (user != null)
                {
                    viewModel.User_Name = user.UserName.Remove(user.UserName.Length - usersNameOrganizati.Length - 1);
                    viewModel.LockoutEnabled = user.LockoutEnabled;
                }

                resultView.Add(viewModel);
            }
            return View(resultView);
        }

        // GET: Admin/Drivers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver drivers = _unitOfWork.GetRepositoryInstance<Driver>().GetFirstOrDefaultByParameter(o => o.Id == id);
            if (drivers == null)
            {
                return HttpNotFound();
            }
            return View(drivers);
        }

        public string GetLatLongByAddress(ref string message, string address)
        {
            string result = "";
            try
            {
                var locationService = new GoogleLocationService();
                var point = locationService.GetLatLongFromAddress(address);

                var latitude = point.Latitude;
                var longitude = point.Longitude;
                result = latitude.ToString() + ":" + longitude.ToString();
            }
            catch (Exception ex)
            {
                message = "Lỗi lấy lat lng address: " + ex.Message;
            }
            return result;
        }

        //public string UploadImageDriver(HttpPostedFileBase file, ref string fileNameOut)
        //{
        //    string message = "";
        //    string fileName = "";
        //    try
        //    {
        //        if (file != null && file.ContentLength > 0)
        //        {
        //            //kiem tra file extension lan nua
        //            List<string> excelExtension = new List<string>();
        //            excelExtension.Add(".png");
        //            excelExtension.Add(".jpg");
        //            excelExtension.Add(".gif");
        //            var extension = Path.GetExtension(file.FileName);
        //            if (!excelExtension.Contains(extension.ToLower()))
        //            {
        //                return "File không đúng định dạng cho phép, bạn hãy chọn file có định dạng .jpg, gif hoặc png";
        //            }
        //            //kiem tra dung luong file
        //            var fileSize = file.ContentLength;
        //            var fileMB = (fileSize / 1024f) / 1024f;
        //            if (fileMB > 5)
        //            {
        //                return "Dung lượng ảnh không được lớn hơn 5MB";
        //            }
        //            // luu ra dia
        //            fileName = Path.GetFileNameWithoutExtension(file.FileName);
        //            fileName = fileName + "-" + DateTime.Now.ToString("dd-MM-yy-hh-ss") + extension;
        //            fileNameOut = fileName;
        //            var physicalPath = Path.Combine(Server.MapPath("~/Uploads/Driver"), fileName);
        //            file.SaveAs(physicalPath);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        message = ex.Message;
        //    }

        //    return message;
        //}


        /// <summary>
        /// Uploading and resizing an image, Currently it is used to upload member profile pic, provider service banner image and category image
        /// </summary>
        /// <param name="message"></param>
        /// <param name="originalImage"></param>
        /// <param name="imageName"></param>
        /// <param name="rootPathOriginal"></param>
        /// <param name="rootPathThumbNail"></param>
        /// <param name="server"></param>
        private void UploadImage(ref string message, HttpPostedFileBase originalImage, string imageName, string rootPathOriginal, string rootPathThumbNail, HttpServerUtilityBase server)
        {
            int MaxContentLength = 1024 * 1024 * 2; //Size = 1 MB  
            if (imageName.LastIndexOf('.') < 0)
            {
                message = string.Format("Định dạng ảnh upload .jpeg,.jpg,.gif,.png.");
                return;
            }

            IList<string> AllowedFileExtensions = new List<string> { ".jpg", ".jpeg", ".gif", ".png" };
            var ext = imageName.Substring(imageName.LastIndexOf('.'));
            var extension = ext.ToLower();
            if (!AllowedFileExtensions.Contains(extension))
            {

                message = string.Format("Định dạng ảnh upload .jpeg,.jpg,.gif,.png.");
                return;
            }
            else if (originalImage.ContentLength > MaxContentLength)
            {

                message = string.Format("Dung lượng file vượt quá 1 mb.");
                return;
            }
            try
            {
                bool existsOriginal = Directory.Exists(PublicConstant.IMAGE_PAHT_TEMP);
                if (!existsOriginal)
                {
                    Directory.CreateDirectory(PublicConstant.IMAGE_PAHT_TEMP);
                }
                originalImage.SaveAs(PublicConstant.IMAGE_PAHT_TEMP + "/" + imageName);

                WebImage img1 = new WebImage(PublicConstant.IMAGE_PAHT_TEMP + "/" + imageName);
                img1.Resize(849, 320);
                bool exists = Directory.Exists(rootPathOriginal);
                if (!exists)
                    Directory.CreateDirectory(rootPathOriginal);
                img1.Save(System.IO.Path.Combine(rootPathOriginal + "/" + imageName));

                WebImage img2 = new WebImage(PublicConstant.IMAGE_PAHT_TEMP + "/" + imageName);
                img2.Resize(274, 175);
                bool exists2 = Directory.Exists(rootPathThumbNail);
                if (!exists2)
                    Directory.CreateDirectory(rootPathThumbNail);
                img2.Save(System.IO.Path.Combine(rootPathThumbNail + "/" + imageName));

src/Carrier.CMS/Areas/Enterprise/Views/EDriver/Details.cshtml
@model Carrier.Models.Entities.Driver
@using Carrier.Utilities
@{
    Layout = "~/Areas/Enterprise/Views/Shared/_LayoutACE.cshtml";
    ViewBag.Title = "Thông tin tài xế";
}
<style type="text/css">
    .form-horizontal .control-label {
        padding-top: 0px !important;
    }
</style>
<h3 style="text-align:center">Thông tin tài xế</h3>

<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right">Tên tài xế</label>
        <div class="col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </div>
    </div>
</div>
<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right">Địa chỉ</label>
        <div class="col-sm-9">
            @Html.DisplayFor(model => model.Address)
            <br />
            <div style="border: 1px solid gray; height:400px; margin-top:20px" id="map">
            </div>
            <div id="infowindow-content">
                <img src="" width="16" height="16" id="place-icon">
                <span id="place-name" class="title"></span><br>
                <span id="place-address"></span>
            </div>
        </div>
    </div>
</div>
<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right">Điện thoại liên hệ</label>
        <div class="col-sm-9">
            @Html.DisplayFor(model => model.Phone)
        </div>
    </div>
</div>

<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right">Giới tính</label>
        <div class="col-sm-9">
            @Html.DisplayFor(model => model.Sex)
        </div>
    </div>
</div>

<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right">Ngày sinh</label>
        <div class="col-sm-9 form-inline">
            @Html.DisplayFor(model => model.BirthDay)
        </div>
    </div>
</div>

@*<div class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right">Nhà xe</label>
            <div class="col-sm-9">
                @Html.DisplayFor(model => model.OrganizationId)
            </div>
        </div>
    </div>*@

@*<div class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right">Vị trí</label>
            <div class="col-sm-9 form-inline">
                @Html.DisplayFor(model => model.Lng)
            </div>
        </div>
    </div>*@

<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right">Ảnh mặt trước</label>
        <div class="col-sm-9 form-inline">
            @if (Model.Front_Image != null)
            {
                <div class="divimage">
                    <img src="@Model.Front_Image" width="150" />
                </div>
            }
        </div>
    </div>
</div>

<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right">Ảnh mặt sau</label>
        <div class="col-sm-9 form-inline">
            @if (Model.Front_Image != null)
            {
                <div class="divimage">
                    <img src="@Model.Back_Image" width="150" />
                </div>
            }
        </div>
    </div>
</div>

<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right">Trạng thái</label>
        <div class="col-sm-9">
            @Html.DropDownList(Model.Status.ToString(), new SelectListItem[]{
                new SelectListItem() { Text = "Đang chờ", Value = "0"},
                new SelectListItem() { Text = "Đang chạy", Value = "1"},
                }, new { @id = "Status", @name = "Status", @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3"></div>
        <div class="col-md-9">
            <span class="lb-Check" id="Status_NULL" style="margin-left: 0px; color:red"></span>
        </div>
    </div>
</div>

<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-3"></div>
        <div class="col-md-9">
            @Html.ActionLink("Cập nhật", "Edit", "EDriver", new { id = Model.Id }, new { @class = "btn btn-info btn-sm" }) &nbsp;&nbsp;
            @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-info btn-sm" })
        </div>
    </div>
</div>
@*google map*@
<script src="~/scripts/jquery1.12.4.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgl7iKcAYPfp-qqi2ug-hCkyOS07osR3U&libraries=places&callback=initMap"
        async defer></script>
<script>
    var map;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            mapTypeControl: false,
            center: {lat: 21.027764, lng: 105.834160},
            zoom: 17
        });

        loadLocation(map,@Model.Lat, @Model.Lng);
    }

    function loadLocation(map,lat, lng) {
        var mapSrc =map;
        var pos = {
            lat: parseFloat(lat),
            lng: parseFloat(lng)
        };

        mapSrc.setCenter(pos);

        var marker = new google.maps.Marker({
            map: mapSrc,
            position:  {lat: parseFloat(lat) , lng: parseFloat(lng)},
            draggable: false,
            size : new google.maps.Size(12, 32)
        });
    }
</script>
@*google map*@

src/Carrier.CMS/Areas/Enterprise/Views/EDriver/ResetPassword.cshtml
@{
    ViewBag.Title = "ResetPassword";
    Layout = "~/Areas/Enterprise/Views/Shared/_LayoutACE.cshtml";
}

@using (Html.BeginForm("ResetPassword", "EDriver", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="col-lg-2"></div>
        <div class="col-lg-6">
            <div class="center wow fadeInDown">
                <h2 style="text-align:center">Reset mật khẩu</h2>
                <hr style="height:2px;width:180px;border:none;color:#333;background-color:#c52d2f;" />
            </div>
            <div class="col">
                <label class="control-label col-md-4">Mật khẩu mới</label>
                <input type="text" name="Newpass" id="txtNewpass" value="" style="width:200px" />
                <button class="btn btn-xs btn-danger" title="Đặt lại mật khẩu" id="resetPass">
                    <i class="ace-icon fa fa-key align-top bigger-120"></i>
                </button>
                <span class="txtNewpass text-danger"></span>

            </div>

            <div class="col">
                <label class="control-label col-md-4"></label>
                <div class="col-md-8" style="width:300px; margin-top:30px">
                    <input type="submit" id="btnChange" value="Reset mật khâu" class="btn btn-primary" style="background: #0066c0; color: #FFF;" />
                </div>
            </div>
        </div>

        <div class="col-lg-3"></div>
    </div>
}
<div>
    @Html.ActionLink("Trở lại danh sách", "Index")
</div>
<script>
    $(document).ready(function () {
        $("#btnChange").bind("click", function (e) {
            $.ajax({

            })
        })
    })
    $(document).ready(function () {
        //var newssPass = $("#txtNewpass").val();
        $("#resetPass").bind("click", (function (e) {
            $.ajax({
                method: "GET",
                contentType: "application/json",
                url: "@Url.Action("setPassword", "EDriver")",
                //data: { 'newssPass': pass },
                success: function (result) {
                    {
                        $("#txtNewpass").val(result);
                    }
                },
                error: function (req, status, error) {
                    // do something with error
                }
            });
            return false;
        }));
    });
</script>

src/Carrier.CMS/Areas/Enterprise/Views/EDriver/_CarDetail.cshtml
@model Carrier.Models.Entities.Car
<style>
    .dl-horizontal dd {
        height: 30px;
    }
</style>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Chi tiết xe</h4>
</div>
<div class="modal-body">
    <dl class="dl-horizontal">
        <dt>
            Biển số
        </dt>

        <dd>
            @Html.DisplayFor(model => model.License)
        </dd>

        <dt>
            Trọng tải (tấn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payload)
        </dd>

        <dt>
            Kích thước thùng 
        </dt>

        <dd>
           @Model.Leng_Size x @Model.Width_Size x @Model.Height_Size
        </dd>

        <dt>
            Mô tả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    <div class="row">
        &nbsp;
    </div>
</div>

src/Carrier.CMS/Areas/Enterprise/Views/EDriver/_ListCar.cshtml
@*@model PagedList.IPagedList<Carrier.CMS.Models.CarInfo>*@
@model IEnumerable<Carrier.CMS.Models.CarInfo>
@using Carrier.Utilities;
@using PagedList.Mvc;
@using Carrier.Utilities
<div class="page-header">
    <h1>Danh sách xe</h1>
</div>
<style>
    .pagination-container {
        margin-left: 30px;
    }

    #car-table {
        width: 90%;
        margin-left: 30px;
    }
</style>
@*@using (Html.BeginForm("ListCarInfo", "EDriver", FormMethod.Get))
    {*@
<div class="row">
    <div class="col-sm-6" style="width:unset;margin-left:30px">Tìm kiếm: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { style = "width: 150px;height: 33px; border-radius: 4px; margin-bottom:10px" })</div>
    <div class="col-sm-3">
        <span>Hiển thị:</span> @Html.TextBox("pagsiz", ViewBag.PageSize as string, new { style = "width: 50px;height: 33px; border-radius: 4px; margin-bottom:10px" })
    </div>
    <input type="submit" value="Tìm kiếm" class="btn btn-info btn-sm" style="margin: -3px 0px 0px 60px" onclick="SearchCar()" />
</div>
@*}*@
<table id="car-table" class="wapperpager table table-bordered table-hover dataTable" style="table-layout:fixed">
    <thead>
        <tr>
            <th class="center" style="width:30px; display:none">
                <label class="pos-rel" style="display:none">
                    <input type="checkbox" class="ace cball">
                    <span class="lbl"></span>
                </label>
            </th>
            <th>
                Biển số
            </th>
            <th>
                Trọng lượng (tấn)
            </th>
            <th style="width:200px">
                Kích thước thùng (m khối)
            </th>
            <th style="width:70px"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="GanXe('@item.Id')">
                <td class="center" style="display:none">
                    <label class="pos-rel" style="display:none">
                        <input type="checkbox" class="ace cbitem">
                        <span class="lbl"></span>
                        <input type="hidden" id="hdfCarId" class="hdfId" name="hdfCarId" value="@item.Id" />
                        <input type="hidden" id="hdfDriverId" class="hdfId" name="hdfDriverId" value="@item.DriverId" />
                    </label>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.License)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Payload)
                </td>
                <td>
                    @item.Leng_Size x @item.Width_Size x @item.Height_Size
                </td>
                <td>
                    <button style="border:none; background:none" title="Gán xe cho tài xế" onclick="GanXe('@item.Id')">
                        <img src="~/Images/icons/car.png" style="height:30px" title="Gán xe cho tài xế" onclick="GetDriverId('@item.DriverId')" />
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>
@*<br />
<span style="margin-left:30px">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</span>

@Html.PagedListPager(Model, page => Url.Action("ListCarInfo",
    new { page, currentFilter = ViewBag.CurrentFilter, pagsiz = @ViewBag.PageSize }))*@

<script>
    $(document).ready(function () {
        $('#car-table tr td:first-child').each(function () {
            var driverId = $(this).find('input[type="hidden"][name="hdfDriverId"]').attr('value');
            sessionStorage.setItem('driverId', driverId);
        });
    })
    function GetDriverId(id) {
        var driverId = id;
        sessionStorage.setItem('driverId', driverId);
    };
    function GanXe(id) {
        var carId = id;
        var driverId = sessionStorage.getItem('driverId');
        $.ajax({
            type: "GET",
            url: "/EDriver/GetCarToDriver",
            data: {
                carId: carId,
                driverId: driverId
            },
            dataType: "json",
            contentType: 'application/json',
            success: function (result) {
                if (result == "OK") {
                    ShowMessage("Gán xe thành công");
                    setTimeout(function () { $('#myModal').hide(); }, 1500);
                    location.reload();
                }
            },
            error: function (req, status, error) {
                // do something with error
            }
        });
    };

    function SearchCar() {
        var searchString = $("#SearchString").val();
        alert(searchString);
        $("#car-table").load('@(Url.Action("ListCarInfo", "EDriver", null, Request.Url.Scheme))?id=' + id+'&searchString='+searchString+'&pagsiz='+10);
        var id =sessionStorage.getItem('driverId');
        $.ajax({
            type: "GET",
            url: "/EDriver/ListCarInfo",
            data: {
                id:id,
                searchString: "29",
                pagsiz:10
            },
            dataType: "json",
            contentType: 'application/json',
            success: function (result) {
                if (result == "OK") {
                    @*$("#dvCategoryResults").load('@(Url.Action("GetCategoryProducts","Home",null, Request.Url.Scheme))?categoryId=' + categoryId);*@
                }
            },
            error: function (req, status, error) {
                // do something with error
            }
        });
    };
</script>


<script src="~/assets/js/jquery-ui.custom.min.js"></script>
<script src="~/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="~/assets/js/chosen.jquery.min.js"></script>
<script src="~/assets/js/fuelux.spinner.min.js"></script>

<script src="~/assets/js/bootstrap-datepicker.min.js"></script>
<script src="~/assets/js/bootstrap-timepicker.min.js"></script>
<script src="~/assets/js/moment.min.js"></script>
<script src="~/assets/js/daterangepicker.min.js"></script>
<script src="~/assets/js/bootstrap-datetimepicker.min.js"></script>
<script src="~/assets/js/bootstrap-colorpicker.min.js"></script>
<script src="~/assets/js/jquery.knob.min.js"></script>
<script src="~/assets/js/jquery.autosize.min.js"></script>
<script src="~/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
<script src="~/assets/js/jquery.maskedinput.min.js"></script>
<script src="~/assets/js/bootstrap-tag.min.js"></script>